receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otelcol'
        scrape_interval: 5s
        static_configs:
        - targets: ['0.0.0.0:8888']
      - job_name: 'node'
        scrape_interval: 5s
        static_configs:
        - targets: ['localhost:9100']
      - job_name: 'l3af'
        scrape_interval: 5s
        static_configs:
        - targets: ['localhost:8898']
      
processors:
  batch:

exporters:
  prometheusremotewrite: 
    endpoint:

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]